#!/usr/bin/expect

set timeout 3
set ip [lindex $argv 0]
set user [lindex $argv 1]
set password [lindex $argv 2]
set wlsun [lindex $argv 3]
set wlsps [lindex $argv 4]
set wlsurl [lindex $argv 5]

spawn ssh "$user\@$ip"

expect "Password:"

send "$password\r";
expect "$ "
send "cd ~/automation/JMS\r"
expect "$ "
send "sh jms_create.sh $wlsun $wlsps $wlsurl | cat >> logs.txt \r exit \r"
interact
