package com.ragsInfo.entity;
// Generated Dec 26, 2018 5:01:43 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private Integer companyId;
	private City city;
	private Country country;
	private State state;
	private String companyName;
	private int tinNumber;
	private String street;
	private String address;

	
	private String countryName;
	private String cityName;
	private String stateName;
	
	public Company() {
	}

	public Company(int tinNumber) {
		this.tinNumber = tinNumber;
	}

	public Company(City city, Country country, State state, String companyName, int tinNumber, String street,
			String address) {
		this.city = city;
		this.country = country;
		this.state = state;
		this.companyName = companyName;
		this.tinNumber = tinNumber;
		this.street = street;
		this.address = address;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}


	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public int getTinNumber() {
		return tinNumber;
	}

	public void setTinNumber(int tinNumber) {
		this.tinNumber = tinNumber;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCountryName() {
		return countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getStateName() {
		return stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}
	
	
	

}
