package com.ragsInfo.entity;
// Generated Dec 28, 2018 3:08:23 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Tagging generated by hbm2java
 */
public class Tagging implements java.io.Serializable {

	private Integer tagId;
	private String tagName;
	private Set users = new HashSet(0);
	private boolean selectedTag;

	public boolean isSelectedTag() {
		return selectedTag;
	}

	public void setSelectedTag(boolean selectedTag) {
		this.selectedTag = selectedTag;
	}

	public Tagging() {
	}

	public Tagging(String tagName) {
		this.tagName = tagName;
	}

	public Tagging(String tagName, Set users) {
		this.tagName = tagName;
		this.users = users;
	}

	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
