package com.journaldev.hibernate.entity;
// Generated Dec 26, 2018 5:01:43 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * State generated by hbm2java
 */
public class State implements java.io.Serializable {

	private Integer stateId;
	private Country country;
	private String state;
	private Set companies = new HashSet(0);
	private Set cities = new HashSet(0);

	public State() {
	}

	public State(String state) {
		this.state = state;
	}

	public State(Country country, String state, Set companies, Set cities) {
		this.country = country;
		this.state = state;
		this.companies = companies;
		this.cities = cities;
	}

	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Set getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set companies) {
		this.companies = companies;
	}

	public Set getCities() {
		return this.cities;
	}

	public void setCities(Set cities) {
		this.cities = cities;
	}

}
