package com.journaldev.hibernate.entity;
// Generated Dec 26, 2018 5:01:43 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer cityId;
	private State state;
	private String city;
	private Set companies = new HashSet(0);

	public City() {
	}

	public City(String city) {
		this.city = city;
	}

	public City(State state, String city, Set companies) {
		this.state = state;
		this.city = city;
		this.companies = companies;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Set getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set companies) {
		this.companies = companies;
	}

}
