package com.journaldev.hibernate.entity;
// Generated Dec 24, 2018 3:55:54 PM by Hibernate Tools 5.3.0.Beta2

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private int cityId;
	private State state;
	private String city;

	public City() {
	}

	public City(String city) {
		this.city = city;
	}

	public City(State state, String city) {
		this.state = state;
		this.city = city;
	}

	public int getCityId() {
		return this.cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}

	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
