package com.journaldev.hibernate.entity;
// Generated Dec 24, 2018 3:55:54 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private int companyId;
	private String companyName;
	private int tinNumber;
	private String street;
	private String state;
	private String country;
	private String city;
	private String address;

	public Company() {
	}

	public Company(int tinNumber) {
		this.tinNumber = tinNumber;
	}

	public Company(String companyName, int tinNumber, String street, String state, String country, String city,
			String address) {
		this.companyName = companyName;
		this.tinNumber = tinNumber;
		this.street = street;
		this.state = state;
		this.country = country;
		this.city = city;
		this.address = address;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	
	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public int getTinNumber() {
		return tinNumber;
	}

	public void setTinNumber(int tinNumber) {
		this.tinNumber = tinNumber;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
