package com.journaldev.hibernate.entity;
// Generated Dec 24, 2018 3:55:54 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {

	private int countryId;
	private String country;
	private Set states = new HashSet(0);

	public Country() {
	}

	public Country(String country) {
		this.country = country;
	}

	public Country(String country, Set states) {
		this.country = country;
		this.states = states;
	}

	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Set getStates() {
		return this.states;
	}

	public void setStates(Set states) {
		this.states = states;
	}

}
