package com.journaldev.hibernate.entity;
// Generated Dec 10, 2018 2:37:24 PM by Hibernate Tools 5.3.0.Beta2

/**
 * User generated by hbm2java
 */
public class Login implements java.io.Serializable {

	   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String username;
     
	    private String password;
	 
	    public String getUsername() {
	        return username;
	    }
	 
	    public void setUsername(String username) {
	        this.username = username;
	    }
	 
	    public String getPassword() {
	        return password;
	    }
	 
	    public void setPassword(String password) {
	        this.password = password;
	    }
}
