package com.journaldev.hibernate.entity;
// Generated Dec 14, 2018 12:43:04 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

import com.journaldev.constants.Month;

/**
 * Role generated by hbm2java
 */
public class ReportData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String month;
	private Date date;
	private String reportNameToView;

	public String getReportNameToView() {
		return reportNameToView;
	}

	public void setReportNameToView(String reportNameToView) {
		this.reportNameToView = reportNameToView;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public Month[] getMonths() {
        return Month.values();
    }
}
