package com.journaldev.hibernate.entity;
// Generated Dec 24, 2018 3:55:54 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * State generated by hbm2java
 */
public class State implements java.io.Serializable {

	private int stateId;
	private Country country;
	private String state;
	private Set cities = new HashSet(0);

	public State() {
	}

	public State(String state) {
		this.state = state;
	}

	public State(Country country, String state, Set cities) {
		this.country = country;
		this.state = state;
		this.cities = cities;
	}

	public int getStateId() {
		return this.stateId;
	}

	public void setStateId(int stateId) {
		this.stateId = stateId;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Set getCities() {
		return this.cities;
	}

	public void setCities(Set cities) {
		this.cities = cities;
	}

}
