package com.journaldev.hibernate.entity;
// Generated Dec 10, 2018 2:37:24 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String firstname;
	private String lastname;
	private Integer age;
	private String street;
	private String city;
	private String info;
	private String email;
	private String phone;
	private Date joinDate;
	private byte status;

	public User() {
	}

	public User(String firstname, String lastname, byte status) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.status = status;
	}

	public User(String firstname, String lastname, Integer age, String street, String city, String info, String email,
			String phone, Date joinDate, byte status) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.age = age;
		this.street = street;
		this.city = city;
		this.info = info;
		this.email = email;
		this.phone = phone;
		this.joinDate = joinDate;
		this.status = status;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
